In [1]:
# _*_ coding: utf-8 _*_

In [2]:
import numpy as np

In [3]:
# sigmoid激活函数
def sigmoid(x):
    return 1/(1+np.exp(-x))

关于权值矩阵
* 第八个参数一行
[w85,w86.w87]
* 第九个参数一行
[w95,w96,w97]

* 输出层误差  
[δ8]  
[δ9]

85δ8 + 95δ9  
86δ8 + 96δ9  
87δ8 + 97δ9  

关于更新权值  
第一层：3*4  
δ5x1+δ5x2+δ5x3+δ5x4  
δ6x1+δ6x2+δ6x3+δ6x4  
δ7x1+δ7x2+δ7x3+δ7x4  

第二层：2*3  
δ8a5+δ8a6+δ8a7  
δ9a5+δ9a6+δ9a7  

In [28]:
# BP函数
def BP(input1,real,w1,w2):
    for s in range(100):
        # 前向传播（隐层a，输出层y）
        output1 = sigmoid(np.dot(w1, input1)) # 第一层输出，输入向量由4*1变成3*1
        output2 = sigmoid(np.dot(w2, output1)) # 第二层输出，输入向量由3*1变成2*1
        
        # 计算损失
        cost = np.square(real-output2)/2 # 计算Ed，目标函数：误差平方和
        
        # 计算误差
        delta2 = output2*(1-output2)*(real-output2) # 计算误差δ2，输出层误差
        delta1 = output1*(1-output1)*w2.T.dot(delta2) # 计算误差δ1，输出3*1
    
        # 更新权值，学习率为1，没有偏置项
        w1 = w1 + delta1.dot(input1.T)
        w2 = w2 + delta2.dot(output1.T)
        
        # 打印查看结果
        print("---round"+str(s)+"---")
        print("output1结果\n"+ str(output1))
        print("output1结果\n"+ str(output2))
        print("损失函数值\n"+ str(cost))
        print("\n")
        

BP的编写
* 输入层：四个节点
* 隐含层：三个节点
* 输出层：两个节点

In [29]:
# 输入数据(四个特征输入：4*1)
input1 = np.array([[0.35], [0.9], [0.58], [0.78]])

# 第一层权值矩阵（初始随意赋值）
w1 = np.random.rand(3,4)
# print(w1)

# 第二层权值参数（初始随意赋值）
w2 = np.random.rand(2,3)

# 输出标签
real = np.array([[0.5],[0.7]])

# 调用BP函数
BP(input1,real,w1,w2)

---round0---
output1结果
[[0.86874726]
 [0.83386345]
 [0.82503889]]
output1结果
[[0.74578809]
 [0.82525712]]
损失函数值
[[0.03020589]
 [0.00784467]]


---round1---
output1结果
[[0.86783881]
 [0.83262949]
 [0.8242086 ]]
output1结果
[[0.72628344]
 [0.81935703]]
损失函数值
[[0.0256021 ]
 [0.00712305]]


---round2---
output1结果
[[0.8670016 ]
 [0.83149029]
 [0.82347485]]
output1结果
[[0.70667367]
 [0.81347556]]
损失函数值
[[0.021357  ]
 [0.00643835]]


---round3---
output1结果
[[0.86624091]
 [0.83044926]
 [0.82283616]]
output1结果
[[0.68732604]
 [0.80763884]]
损失函数值
[[0.01754552]
 [0.00579306]]


---round4---
output1结果
[[0.86555878]
 [0.82950592]
 [0.82228738]]
output1结果
[[0.66858854]
 [0.80187183]]
损失函数值
[[0.01421105]
 [0.00518894]]


---round5---
output1结果
[[0.8649542 ]
 [0.82865639]
 [0.82182053]]
output1结果
[[0.65075921]
 [0.79619803]]
损失函数值
[[0.01136417]
 [0.00462703]]


---round6---
output1结果
[[0.86442358]
 [0.82789426]
 [0.8214259 ]]
output1结果
[[0.63406567]
 [0.79063923]]
损失函数值
[[0.0089868 ]
 [0.00410773]]


---rou